version: '3.8'

services:
  haproxy:
    image: haproxy:2.6
    container_name: haproxy_lb
    ports:
      - "8081:80"
      - "8080:8080"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - haproxy_socket:/tmp/
    networks:
      - cluster_network

  backend1:
    build: ./backends
    container_name: backend1
    networks:
      - cluster_network

  backend2:
    build: ./backends
    container_name: backend2
    networks:
      - cluster_network

  backend3:
    build: ./backends
    container_name: backend3
    networks:
      - cluster_network

  datadog:
    image: registry.datadoghq.com/agent:7
    container_name: dd-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./datadog/datadog.yaml:/etc/datadog-agent/datadog.yaml:ro
      - ./datadog/haproxy.d:/etc/datadog-agent/conf.d/haproxy.d:ro
      - haproxy_socket:/tmp/
    networks:
      - cluster_network

networks:
  cluster_network:
    driver: bridge

volumes:
  haproxy_socket: